# Generated by Django 3.2.6 on 2021-08-31 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField()),
                ('titulo', models.CharField(max_length=30)),
                ('resumen', models.CharField(max_length=100)),
                ('vistas', models.IntegerField(max_length=30)),
                ('archivo', models.FileField(upload_to='')),
                ('imagen', models.ImageField(upload_to='')),
                ('autores', models.ManyToManyField(to='sitio.Autor')),
                ('comentarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.comentario')),
            ],
        ),
    ]
