# Generated by Django 3.2.6 on 2021-09-01 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0003_alter_publicacion_vistas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='archivo',
        ),
    ]
