# Generated by Django 3.2.6 on 2021-09-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0005_auto_20210901_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='archivo',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='vistas',
            field=models.IntegerField(null=True),
        ),
    ]
