# Generated by Django 3.2.6 on 2021-09-01 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0006_auto_20210901_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='comentarios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.comentario'),
        ),
    ]
