# Generated by Django 3.2.6 on 2021-09-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0007_alter_publicacion_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
