# Generated by Django 3.2.6 on 2021-09-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0008_alter_publicacion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
