# Generated by Django 3.2.6 on 2021-09-02 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0009_auto_20210902_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='comentarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.comentario'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='vistas',
            field=models.IntegerField(default=0),
        ),
    ]
