# Generated by Django 3.2.6 on 2021-09-02 13:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0010_auto_20210902_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='archivo',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
