# Generated by Django 3.2.6 on 2021-09-05 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0011_auto_20210902_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='autores',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='autores',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='sitio.autor'),
            preserve_default=False,
        ),
    ]
