# Generated by Django 3.2.6 on 2021-09-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0012_auto_20210905_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='autores',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='autores',
            field=models.ManyToManyField(to='sitio.Autor'),
        ),
    ]
