# Generated by Django 3.2.6 on 2021-09-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0013_auto_20210905_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='resumen',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
