# Generated by Django 3.2.6 on 2021-09-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0014_auto_20210907_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='archivo',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
