# Generated by Django 3.2.6 on 2021-09-09 14:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def clear_old_migrations(apps, schemas):
    model = apps.get_model('sitio', 'Publicacion')
    model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0016_auto_20210907_1051'),
    ]

    operations = [
        migrations.RunPython(clear_old_migrations),
        migrations.AddField(
            model_name='publicacion',
            name='usuario',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to='sitio.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
