# Generated by Django 3.2.7 on 2021-09-10 11:00

from django.db import migrations, models
import sitio.models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0017_auto_20210909_1100'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', sitio.models.UsuarioManager()),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.IntegerField(choices=[(1, 'VERIFICADO'), (2, 'NO VERIFICADO'), (3, 'BLOQUEADO PERM'), (4, 'BLOQUEADO TEMP')], default=2),
        ),
        migrations.AddField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
