# Generated by Django 3.2.7 on 2021-09-11 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0017_auto_20210907_1809'),
        ('sitio', '0019_alter_usuario_email'),
    ]

    operations = [
    ]
