# Generated by Django 3.2.6 on 2021-09-16 22:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0020_merge_20210911_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='año_creacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
