# Generated by Django 3.2.6 on 2021-09-18 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0021_publicacion_año_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='estado',
            field=models.CharField(choices=[('publicada', 'La publicación está activa'), ('borrador', 'La publicación está siendo escrita y no activa'), ('en_revision', 'La publicacion esta siendo evaluada por administradores'), ('bloqueada', 'La publicacion no está activa')], default='en_revision', max_length=200),
        ),
    ]
