# Generated by Django 3.2.6 on 2021-09-21 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0023_alter_publicacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='seguidores',
            field=models.ManyToManyField(related_name='_sitio_usuario_seguidores_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='siguiendo',
            field=models.ManyToManyField(related_name='_sitio_usuario_siguiendo_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
