# Generated by Django 3.2.6 on 2021-09-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0024_auto_20210921_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='carrera',
            field=models.IntegerField(choices=[(1, 'Ingenieria'), (2, 'Abogacia'), (3, 'Contaduria')], default=0),
        ),
    ]
