# Generated by Django 3.2.6 on 2021-09-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0025_publicacion_carrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='carrera',
            field=models.IntegerField(choices=[(1, 'Ingenieria en informatica'), (2, 'Abogacia'), (3, 'Contaduria'), (4, 'Medios visuales')], default=1),
        ),
    ]
