# Generated by Django 3.2.6 on 2021-09-24 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0026_alter_publicacion_carrera'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='año_creacion',
            new_name='fecha_publicacion',
        ),
    ]
