# Generated by Django 3.2.6 on 2021-09-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0027_rename_año_creacion_publicacion_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.TextField(max_length=1000),
        ),
    ]
