# Generated by Django 3.2.6 on 2021-09-27 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0028_alter_comentario_texto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='seguidores',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='siguiendo',
        ),
        migrations.AddField(
            model_name='comentario',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sitio.usuario'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_seguimiento', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='siguiendo', to=settings.AUTH_USER_MODEL)),
                ('usuario_siguiendo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='seguidores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
