# Generated by Django 3.2.7 on 2021-09-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0029_auto_20210927_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='archivo',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.FileField(upload_to=''),
        ),
    ]
