# Generated by Django 3.2.6 on 2021-09-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0030_auto_20210927_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seguimiento',
            old_name='usuario',
            new_name='usuario_id',
        ),
        migrations.RenameField(
            model_name='seguimiento',
            old_name='usuario_siguiendo',
            new_name='usuario_siguiendo_id',
        ),
    ]
