# Generated by Django 3.2.6 on 2021-10-05 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0032_auto_20211004_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='u_siguiendo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='usuario_siguiendo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='u_seguidores', to=settings.AUTH_USER_MODEL),
        ),
    ]
