# Generated by Django 3.2.8 on 2021-10-13 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0035_alter_comentario_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='padre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='sitio.comentario'),
        ),
    ]
