# Generated by Django 3.2.8 on 2021-10-19 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0036_comentario_padre'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='responde',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='sitio.comentario'),
        ),
    ]
